name: My First GitHub Action
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 14
            - name: Install node_modules
              run: npm install
            - name: Build the project 
              run: npm run build
            - name: Deploying the project
              env: 
                VERCEL_ORG_ID: EL8sDhVO7MROzeONs9cB1VQR
                VERCEL_PROJECT_ID: prj_nZhocRrQ0SRxTiWfMyjThVpzZSrR    
              run: npm deploy            
            - name: Setup Finish
              run: echo "Hurray"

            
    # print-hello-world2:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - run: echo "Hello world"
    #         - run: echo "This is step number 2"